version: '3.3'
services:
  redis-cluster:
    deploy:
        mode: replicated
        replicas: 6
        restart_policy:
          condition: on-failure
    image: mrchenli/redis-cluster:3.0.0
    environment:
      PORT: 7000
      ZK_HOSTS: zk:2181
      NET_IFACE: eth0
    container_name: redis-cluster
    depends_on:
      - zkui

networks:
  default:
    external:
      name: redis-cluster