version: '3.3'
services:
  redis-cluster:
    deploy:
        mode: replicated
        replicas: 6
        restart_policy:
          condition: on-failure
    image: mrchenli/redis-cluster:1.0.0
    environment:
      PORT: 7000
      ZK_HOSTS: zk:2181
      NET_IFACE: eth0
    container_name: redis-cluster
    depends_on:
      - zkui

  redis-state:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    image: mrchenli/redis-stat:3.0.0
    environment:
      PORT: 7006
      ZK_HOSTS: zk:2181
    container_name: redis-stat
    ports:
    - target: 7006
      published: 7006
      protocol: tcp
      mode: host
    depends_on:
      - redis-cluster

networks:
  default:
    external:
      name: redis-cluster